[global]
address = "0.0.0.0"
environment = "development"
db = "horde.db"
api = "6af73b25-2432-4b79-af86-e7a14da8debc"

[development.server]
port = 8000

[staging.server]
port = 8000

[production.server]
port = 8000
